# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: windows-latest

steps:
#- task: AzureCLI@2
#  inputs:
#    azureSubscription: 'Static-Web-Connection' # (Connection set for Ray's Sub)
#    scriptType: bash
#    scriptLocation: inlineScript
#    inlineScript: |
#      az deployment sub create --location eastus --template-file Static-Web-Infrastructure/CDNStaticWebsite.bicep --parameters projectName=$(projectName) environment=$(environment)
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'Static-Web-Connection'
    subscriptionId: '28e62442-8bc7-4e32-8792-7b6f570861ba'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: './Static-Web-Infrastructure/CDNStaticWebsite.bicep'
    overrideParameters: -projectName $(projectName) -environment $(environment)
    deploymentMode: 'Incremental'
    deploymentOutputs: storageAccName
#- task: PowerShell@2
#  inputs:
#    targetType: 'inline'
#    script: |
#     $outputs = ConvertFrom-Json '$($env:storageAccName)'
#      foreach ($ouput in $outputs.PSObject.Properties) {
#      Write-Host "##vso[task.setvariable variable=ARMDO_$($output.Name)]$($output.Value.value)"
#      }
- task: AzureCLI@2
  inputs:
     azureSubscription: 'Static-Web-Connection'
     scriptType: 'bash'
     scriptLocation: 'inlineScript'
     inlineScript: |
      '#!/bin/bash
      KEY=$(az storage account keys list -n armOutputVariable.storageAccName.value --query [0].value -o tsv)
      az storage blob upload-batch --source ./* --destination https://$(armOutputVariable.storageAccName.value).blob.core.windows.net/$web --account-name $(armOutputVariable.storageAccName.value) --account-key $(KEY)'

#- task: AzureFileCopy@4
#  inputs: 
#    sourcePath: './*'
#    azureSubscription: 'Static-Web-Connection' # (Connection set for Ray's Sub)
#    destination: azureBlob
#    storage: $(armOutputVariable.storageAccName.value) 
#    containerName: $web
   