# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Website-Update-VG

steps:
- task: sftpupload@1
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
      EmissionReport.pdf
      whoweare.html
    targetFolder: '/'
    host: '$(IONOS-host)'
    port: '22'
    username: '$(IONOS-user)'
    password: '$(IONOS-pass)'
# - task: sftpupload@1
#   inputs:
#     sourceFolder: '$(Build.SourcesDirectory)'
#     contents: |
#       certificates/**
#       css/**
#       fonts/**
#       iconset/**
#       images/**
#       js/**
#       rapid/**
#       testcareers/**
#       videos/**
#       capabilities.html
#       careers.html
#       contact.html
#       contracts.html
#       EmissionReport.pdf
#       index.html
#       jobs.html
#       sustainability.html
#       theresumator_helper.html
#       whoweare.html
#     targetFolder: '/'
#     host: '$(IONOS-host)'
#     port: '22'
#     username: '$(IONOS-user)'
#     password: '$(IONOS-pass)'