# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: windows-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'Static-Web-Connection'
    subscriptionId: '28e62442-8bc7-4e32-8792-7b6f570861ba'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: './Static-Web-Infrastructure/CDNStaticWebsite.bicep'
    overrideParameters: -projectName $(projectName) -environment $(environment)
    deploymentMode: 'Incremental'
    deploymentOutputs: armOutputVariable

- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: AzureCLI@2
  inputs:
     azureSubscription: 'Static-Web-Connection'
     scriptType: 'bash'
     scriptLocation: 'inlineScript'
     inlineScript: |
      #!/bin/bash
      KEY=$(az storage account keys list -g $(armOutputVariable.resourceGroupName.value) -n $(armOutputVariable.storageAccountName.value) --query [0].value -o tsv)
      az storage blob upload-batch --overwrite=True --source '$(Build.ArtifactStagingDirectory)' --destination '$web' --account-name $(armOutputVariable.storageAccountName.value) --account-key $KEY
