name: Lighthouse Audit

on:
  push:
    branches:
      - feature/lighthouse

jobs:
  lighthouse-audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Lighthouse
      run: npm install -g lighthouse

    - name: Run Lighthouse Audit
      run: |
        lighthouse https://kangtamo.github.io/anika-systems-web --output html --output-path ./lighthouse-report.html --chrome-flags="--headless"

    - name: Upload Lighthouse report
      uses: actions/upload-artifact@v3
      with:
        name: lighthouse-report
        path: ./lighthouse-report.html